### ISSUE TITLE
  // , How do I copy and paste text?

### ISSUE THREAD

**Issue by v6** [subliun/Antox#100]
// , I am sending some of the Tox IDs that I have in another client to the installation of subliun's Antox on my phone. 

I would like to add those Tox IDs to my phone. 

However, I cannot copy them easily and securely.

**Comment by zetok** [comment]
duplicate of #42

**Comment by v6** [comment]
// , Is this a wontfix?

**Comment by 00firestar00** [comment]
The easier copy-paste is fixed, There hasn't been any work on the "securely" portion of this ticket
