### ISSUE TITLE
there was no update in fdroid repo since mid june

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#112]
can we expect new repo on tox.chat?

**Comment by subliun** [comment]
I'm working on it. The new google play app will probably come first.

**Comment by starthal** [comment]
The old repo path should probably be removed from README.md in the meantime, as it is currently broken and probably untrustworthy.

**Comment by agilob** [comment]
Why don't you add antox directly to fdroid? This situation would not happen. You can release new app build on every commit in your repository and in F-Droid every Friday/on tag/on version change. If you could post me your build script I can add it to [fdroiddata](https://gitlab.com/fdroid/fdroiddata/) on gitlab.com

**Comment by starthal** [comment]
[This thread](https://f-droid.org/forums/topic/antox/) explains some of the issues. I'm not sure what their current status is.

**Comment by agilob** [comment]
Moderator wrote there:

>I myself would love to see antox in fdroid and will certainly look into this when it’s more mature. If someone else is going to proive updated build recipes, just MR thos on our gitlab repo. I’ll gladly merge them in.

He responded the same [under issue on gitlab](https://gitlab.com/fdroid/fdroiddata/issues/218):
>I still like to have it in fdroid, if it's somewhat stable and maintainable (e.g. not relying on prebuilt binaries, but safely integrate building them into the default build system), but I'll wait for others to update the recipe or even upstream to ping us when they think it's ready.

I don't observe your repository too much, but is there any effort or chance to solve this issue?

**Comment by optimumtact** [comment]
we're in the process of getting our own fdroid repo up for antox

**Comment by ameenross** [comment]
I'm curious about this. Will it be signed with the same key? Last time repos were switched I lost my profile because I had to uninstall. Of course I only realized I had to export my profile after the fact.

**Comment by subliun** [comment]
https://antox.me/fdroid/repo

**Comment by agilob** [comment]
403
