### ISSUE TITLE
Turns out I'm in charge of toxme now.

### ISSUE THREAD

**Issue by subliun** [subliun/Antox#119]
sigh

**Comment by mva1985** [comment]
how's that?  i've been following tox for awhile now

**Comment by stal888** [comment]
![1438984957536](https://cloud.githubusercontent.com/assets/774591/9148589/49782dac-3d36-11e5-89d3-c5c05b03a2c7.jpg)
thanks

**Comment by louipc** [comment]
On Fri 07 Aug 2015 18:14 -0700, subliun wrote:
> sigh

dun dun dunnn.
Good luck. Wish I could make time to help with tox stuff again.

**Comment by ProMcTagonist** [comment]
Cool.

**Comment by subliun** [comment]
now running at https://toxme.io
