### ISSUE TITLE
Not receiving friend requests

### ISSUE THREAD

**Issue by RomanHargrave** [subliun/Antox#124]
I am unable to receive (incoming) friend requests, although I can send them and message people that I have added.

I am using the latest version of Antox (marked as version 0.23, compiled at ea832b5147b4169979049300cb3a6e90bc330997).

There appears to be no logging output.

**Comment by subliun** [comment]
I cannot reproduce this.

**Comment by RomanHargrave** [comment]
Hm. That's odd. Could it be due to firewall misconfiguration on the device?

**Comment by subliun** [comment]
Could be. Though in that case you shouldn't be able to send messages. Did you test receiving FRs from more than one device? It might be an issue with your connection on the non-antox side.

**Comment by RomanHargrave** [comment]
Yes. I can send/receive messages, and can send friend requests. However, a number of people have attempted to friend my phone's ID, and I have received none of those requests.
