### ISSUE TITLE
Antox Colors and Design. 

### ISSUE THREAD

**Issue by dcharles525** [subliun/Antox#13]
The layout is pretty good, just a couple of changes to think about to get it up to material design standards. 

Colors - The colors need a desperate refresh, shouldn't be to hard getting the colors changed: http://www.google.com/design/spec/style/color.html

Layout - The side menu, fab button, and other tiny elements - http://www.google.com/design/spec/layout/principles.html

Other - The profile pictures need to be implemented as well.

Insperation - https://d13yacurqjgara.cloudfront.net/users/131060/screenshots/1764816/attachments/287644/chat.jpg

http://cdn.redmondpie.com/wp-content/uploads/2014/11/14.png

https://www.droidapp.nl/wp-content/uploads/2014/11/telegram1.jpg

I would love to discuss and come up with a full list of things that need to be changed with some suggestions from the community. This is half the battle of making this app go viral.

**Comment by subliun** [comment]
I don't mind the current colour-scheme, but I'm open to looking at alternatives. 
The side menu is something I'd like to fix, it doesn't quite fit with other material apps. 
I cannot implement profile pictures as Tox4j doesn't support them yet.

What else in particular do you think should be improved?

**Comment by dcharles525** [comment]
@subliun 

I have nothing wrong with the current color except it looks a little dull and old, I would just think that matching the colors of qTox and uTox (using google material palette) would be best. 

The tabs take up screen space on the smaller screened phones, I never noticed this until I saw a friend running Antox on a Moto G. The app seems almost to tight. An idea might be merging recent contacts and the contacts section, what you could do is have the most recent conversations at the top like depicted below. 

##### Recent Conversations
###### dcharles     - hey...
###### sublin         - what up playa?
###### irungentoo -  I am a god.
...

Then have a fab button that brings up a page where you can search, add contacts, and message the person. This way it eliminates the tabs and frees up some space. 

Some other smaller things:
1. Add the material notification bar color
2. Consider different colors or maybe be able to pick your own colors??
3. Material animations every where, on tap, when new screen coming up, etc.

I am not able to go and test the current version right now but I will be back with some edits later in the day.

**Comment by subliun** [comment]
I think the best idea would be to work on theme support (night mode, letting people choose their own colour-scheme) so that I can see what people like.

**Comment by dcharles525** [comment]
@subliun Awesome! I know things are very limited for you at the moment because tox4j is still not complete but thank for bringing Antox back from the dead and improving all this.

**Comment by KOLANICH** [comment]
Also we need a pure black theme for amoled screens.

**Comment by subliun** [comment]
Side menu is now material, along with preferences, FAB and basic theme support.
