### ISSUE TITLE
Consistently crashing when sending a message

### ISSUE THREAD

**Issue by donjan** [subliun/Antox#132]
I'm running Antox 0.23.25 with Android 2.3.5 on a HTC Desire S S510e, stock Sense 3.0 ROM.

When sending a message to another mobile client (Antox or Antidote), my Antox crashes (Force close dialog) every time. When sending to a desktop client (qTox), it crashes unless the desktop client has sent something first and is shown as online.
Might be related: in the latter case, sending from qTox to Antox takes 2-3 minutes in the first place.

How do I proceed with providing debug info?

**Comment by subliun** [comment]
Fixed via https://github.com/subliun/Antox/commit/2be6c30d0f23f3285d7ca0ac5e019101500a62cf
