### ISSUE TITLE
Antox crash

### ISSUE THREAD

**Issue by SelfDestruct68** [subliun/Antox#133]
Hi, 

I am running android 5.0.1 touchwiz
Antox 0.23.35

Antox keeps crashing randomly in the background. When I am done talking with people and press the home button or back to do something else the app crashes after a minute or so.

I didn't had the issue with antox v0.23.23

**Comment by SelfDestruct68** [comment]
Seems fixed now with 0.23.37
Thnx!

**Comment by subliun** [comment]
No problem. Sorry about that, it was a little UserDB bug in the background. I'll be setting up automated UI tests sometime in the future to catch this sort of thing before the builds get pushed out.
