### ISSUE TITLE
Recent chats show incorrect avatar

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#137]
First avatar on the list is my avatar, it should be empty as the user on the list didn't accept my friend request. It happens both for my contacts and for contacts awaiting FR acceptance.

![screenshot_2015-08-27-17-20-21](https://cloud.githubusercontent.com/assets/2544251/9562726/aa35a614-4e6c-11e5-888f-31c0f4980a37.png)

**Comment by agilob** [comment]
<3

**Comment by subliun** [comment]
Don't get your hopes too far up. I never actually  tested, but I'm preeettyyy sure I fixed it.

**Comment by agilob** [comment]
</3

**Comment by subliun** [comment]
:P

**Comment by wiiam** [comment]
its probably because you dont have the purple theme
