### ISSUE TITLE
Tall pictures (vertical direction) spam the messaging screen

### ISSUE THREAD

**Issue by Foxdelmar** [subliun/Antox#145]
Hi,
when receiving a pictures and they are big in the vertical direction, they spam the chat screen.

Please add two features:
- resize pictures to a maximum width and heights
- make it possible to delete pictures on long-tapping and add the question wether to delete only in the chat or also on the storage.

Thank you for your work! How can I donate or support besides testing?

Best regards
Fox

**Comment by 00firestar00** [comment]
Try clicking on the edge of the image (the grey/purple padding) you should be able to trigger the longpress event. Its hard to do, but could be a work around until its fixed
