### ISSUE TITLE
403 on https://antox.me/fdroid/repo

### ISSUE THREAD

**Issue by aaannndddyyy** [subliun/Antox#149]
https://antox.me/fdroid/repo  gives 403

**Comment by subliun** [comment]
You have to add it as an F-Droid repo, or you can get the apk from https://antox.me/fdroid/repo/antox.apk
explanation as to why there is no webpage there: https://antox.me

**Comment by aaannndddyyy** [comment]
No, it does not work in fdroid. That's why I wanted to look at the index file with my browser and saw this.

**Comment by subliun** [comment]
Just used the fdroid repo and it works for me. What have you tried?

**Comment by aaannndddyyy** [comment]
I added https://antox.me/fdroid/repo to package sources / repositories in fdroid, then refreshed repositories and it says all repositories refreshed except antox's, error getting index file

**Comment by aaannndddyyy** [comment]
Still not working....

**Comment by Mehonidas** [comment]
Hi aaannndddyyy i have the same trouble!
i loke tox and want test it on android. I hope it coming back soon!

Bye Meho
