### ISSUE TITLE
Antox and qTox on same LAN status connection problems

### ISSUE THREAD

**Issue by Getron** [subliun/Antox#150]
I have the newest qTox on my Fedora 22 KDE, and the same profile exported to my Android Note 3 on the newest Antox. Both are fresh installed today, on 08.09.2015.

The problem is, on my qTox, my status is going crazy, if i connect with the same profile on the same LAN on my Antox.
It connect, and disconnect on every 2-5 seconds on my Desktop instantly.

If i logout on Antox, it is stable again.

I think, this is a conflict, or bug somwhere, if the same profile on both devices.

**Comment by subliun** [comment]
You can't use the same profile on two devices at the same time. This is a toxcore limitation. When proper multi-device support is implemented this will no longer be an issue.
