### ISSUE TITLE
Avatar thumbnail isn't updated after selecting picture

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#176]
^

**Comment by subliun** [comment]
You mean for contacts?

**Comment by subliun** [comment]
It updates instantly for me.

**Comment by agilob** [comment]
1. select picture
2. open drawer
3. you see old picture

**Comment by subliun** [comment]
what do you mean "select picture"? I assume you mean: open settings > select avatar > close settings > open drawer > you see old picture

That's what I tested and I can't reproduce it.

**Comment by agilob** [comment]
You want a video?

**Comment by subliun** [comment]
I would enjoy it. :)

**Comment by subliun** [comment]
Confirmed.

**Comment by agilob** [comment]
I wanted to record it now, but antox doesn't start at all after recent upgrade...

**Comment by subliun** [comment]
A few people have said that. A log would be greatly appreciated.

**Comment by subliun** [comment]
Tempted to close as wontfix after 3 hours of debugging.

**Comment by subliun** [comment]
scratch that I'm an idiot. fixed.
