### ISSUE TITLE
Fdroid repo is unreachable here

### ISSUE THREAD

**Issue by timofonic** [subliun/Antox#187]
I'm unable to access to the repo. Are there a problem or is just me?

**Comment by zoff99** [comment]
+1
since yesterday

**Comment by optimumtact** [comment]
Known issue, we are working on resolving it, apologies about that.

**Comment by Zaukaj** [comment]
I'm having this too, look forward to it being fixed.

**Comment by timofonic** [comment]
Any news about what happened? I want to reinstall Antox after wiping my phone and O don't use Google Services...

**Comment by optimumtact** [comment]
@subliun is hoping to have it resolved today, hopefully he can chime in at somepoint as well and let you know the exact eta.

**Comment by optimumtact** [comment]
should be resolved, apologies for the delay.

**Comment by agilob** [comment]
I see update available, but cannot download it.

**Comment by alice-margatroid** [comment]
@agilob Before you made your post I could download and install it. Just for the sake of testing I deleted and tried to install it again, getting a "not installed" error now. You are right, it's currently not working again.
