### ISSUE TITLE
Broken dependency in build.gradle results in failures

### ISSUE THREAD

**Issue by alice-margatroid** [subliun/Antox#189]
I've been discussing it https://github.com/afollestad/material-dialogs/issues/769 here, but in a nutshell
 compile 'com.afollestad:material-dialogs:0.7.3.0' is not working any more and my attempts to load it from a different repository (i.e. maven { url "https://jitpack.io" }) with the correct commit id (66bf6645cf@aar) didn't work either.

Please help me fix com.afollestad.material-dialogs:core:66bf6645cf@aar so I can get the last dependency I need.

*Edit:*
Astonex\Antox is kill as well, he said he needs more time. I could have gone the easy way and just use the beta release from playstore but this is more fun.

**Comment by agilob** [comment]
SO afollestad decided to fix something that worked and now it's all broken?

**Comment by alice-margatroid** [comment]
I'm not sure where to integrate that into my build process, but thank you for being helpful. I'm willing to try it out. I'm confused though, if you say latest version of dependencies, are you implying that I can go higher than v0.7.3.0 with material-dialogs or will there be issues with Antox?

**Comment by subliun** [comment]
> in the end I still can't get it running and give up.
:'(

I will fix this tonight.

**Comment by dcharles525** [comment]
could this be why I cannot grab the apk from the fdroid repo?

**Comment by subliun** [comment]
you cannot grab the apk from the fdroid repo because it, along with the other services that I run, is down.

**Comment by dcharles525** [comment]
I love and believe in you @subliun. Thanks for the quick response.

**Comment by alice-margatroid** [comment]
@subliun  Thank you a lot for fixing it! I've seen you just removed the dependency for afollestad's material dialogs.
