### ISSUE TITLE
Won't connect to GroupBot.

### ISSUE THREAD

**Issue by DarkLinkXXXX** [subliun/Antox#19]
For some reason, Antox won't connect to GroupBot@toxme.se.
You can add him to the list, but the bot will never appear online.

Edit: Here's my version information and stuff.

![r4w9zd2](https://cloud.githubusercontent.com/assets/767386/6207825/8eb10a7a-b5a4-11e4-8948-2b493263aee3.png)

**Comment by afkgeek** [comment]
What do your settings look like under Antox?
