### ISSUE TITLE
Antox became slow and unresponsive

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#195]
after last changes, resuming antox, sending message, changing skin or anything else that changes UI is very, very slow, like Vista slow.

**Comment by agilob** [comment]
and when I write a few messages quickly antox loses connection with the network, goes offline and I have to wait for it to go online again to write more messages...

**Comment by subliun** [comment]
How many friends do you have and how large are your chatlogs? Is it still slow with a new profile?

**Comment by agilob** [comment]
8 friends; history cleared on Saturday;


I made a new profile and it's not lagging there.

**Comment by subliun** [comment]
Good info, thanks. Time to make some friends and start profiling.

**Comment by agilob** [comment]
1. write 40messages from qtox to antox quickly
2. open chat on antox
3. write a few messages
4. press back
5. ...
6. ...
7. .....
8. ...finally..

**Comment by subliun** [comment]
for me some messages get dropped O_O

**Comment by agilob** [comment]
Because of lagging, yes, this happens too.

**Comment by subliun** [comment]
@agilob should be fixed by the latest commit

**Comment by agilob** [comment]
works better now. thanks.
