### ISSUE TITLE
Fdroid upgrade: Downloaded file is corrupt

### ISSUE THREAD

**Issue by timofonic** [subliun/Antox#206]
Hello.

I tried to upgrade Antox 0.23.96 to 0.23.97 right now, but Fdroid replies me "Downloaded file is corrupt" all the time.

Are there some issue or is my system broken again? Did anyone have the same issue?

Kind regards.

**Comment by agilob** [comment]
No, i Just updates it successfully.

**Comment by dcharles525** [comment]
Works here.

**Comment by timofonic** [comment]
It was a temporal issue, it seems...

**Comment by LapFox** [comment]
I was also getting the same issue, but it seems to have resolved itself.
