### ISSUE TITLE
Notifications sometimes don't appear 

### ISSUE THREAD

**Issue by subliun** [subliun/Antox#214]
Particularly when the app is in the background.

Should be getting a new notification manager for every notification rather than relying on the one acquired in MainActivity.

**Comment by svalo** [comment]
I'm never getting notifications on cyanogen 12.1 on nexus5. I appear -and am- online but don't recive any notification, as soon as I open the app I see all the messages I recived in the meantime. Tought it was the same problem in #43 so didn't report
