### ISSUE TITLE
no fdroid fingerprint

### ISSUE THREAD

**Issue by imkarjala** [subliun/Antox#216]
The fdroid repo is not signed. I realize it is https so from a security aspect that might be fine, but it would still be nice. Also, the current category is "none", giving it a category of " antox" or "tox" or one of the existing categories would also be nice.

Also, is there anywhere I can go to find people to talk to on Tox? I would like to help find bugs and whatnot but that is difficult when I don't have anyone to talk to.....

**Comment by cebe** [comment]
> Also, is there anywhere I can go to find people to talk to on Tox? I would like to help find bugs and whatnot but that is difficult when I don't have anyone to talk to.....

IRC channels: #tox and #tox-dev on [freenode](https://freenode.net/)
If you do not have an IRC client you may use the webchat: https://webchat.freenode.net/

**Comment by ProMcTagonist** [comment]
>find people to talk to on Tox?

You can also add groupbot@toxme.io and message him "invite 0" to join the public groupchat. (I don't think Antox will support groupchats until after their rewrite is done though)

**Comment by subliun** [comment]
I added Antox to the Phone & SMS category.

**Comment by c33s** [comment]
reopen please. 
the fingerprint is still missing. would feel much better having the option to add the fingerprint

**Comment by wiiaam** [comment]
@c33s see https://github.com/Antox/Antox/issues/296
