### ISSUE TITLE
F-Droid download is faulty

### ISSUE THREAD

**Issue by EmJotGeh** [subliun/Antox#218]
Hi, 

Antox update over F-Droid is not possible - download ist faulty?!

**Comment by insanity54** [comment]
Yep, me too. Three or four days ago I could download and install through F-Droid, but now, F-Droid reports the file is corrupt.

screenshot of problem-
https://ipfs.pics/Qmb8vWgxotVQUd1BdiEaefGLBCF87Rc49minRMKPjn5Nto

**Comment by EliahShure** [comment]
Same here for 0.23.185 and 0.23.190

**Comment by svalo** [comment]
Same here, I downloaded 0.23.185 from jenkins and it works

**Comment by subliun** [comment]
This should be fixed now. Sorry for the inconvenience.

**Comment by agilob** [comment]
Works for me now

**Comment by LapFox** [comment]
I'm still unable to update, getting "Download is corrupt"

**Comment by EliahShure** [comment]
Updated repos LapFox?

**Comment by LapFox** [comment]
It fixed itself this morning, fully closed for me
