### ISSUE TITLE
A/V and file transfer

### ISSUE THREAD

**Issue by dionnejkelly** [subliun/Antox#22]
Hey, A/V and file transfer work now ?
Could there be  an option to have the user register with their phone number ? 
No sms verification, just singup with their phone number. An option to choose their area code should be available too...

**Comment by subliun** [comment]
This is currently in the works, but may take a little while. Tox4j currently doesn't support audio calls or file transfers, so I'll be waiting for that before implementing them in Antox.

**Comment by dionnejkelly** [comment]
oh i see.
I have a version on my phone (0.15) that supports file transfer. 
The user avatars not showing up though, neither there is an option to change my avatar.
I guess you are working on this now. Thanks for the great app :)

**Comment by subliun** [comment]
File transfers are done. Audio is in a separate issue.
