### ISSUE TITLE
Export Profile Does Nothing

### ISSUE THREAD

**Issue by gitgud-software** [subliun/Antox#227]
I'm on the latest Paranoid Android build for Oneplus One, and Antox build 0.23.218 via F-Droid. I'm not going to be able to do further testing, since I'm reflashing this device (with no survivors), but attempting to export the user's profile brings up the select directory prompt, tells you the profile has been exported, and never does so.

I suppose if somebody wants to flash Paranoid Android (not that it would be sane; the developers work for Oneplus now and would rather work on Oxygen OS that "do it for free"), I guess they can carry out further analysis.

For now, I'm off to greener pastures hoping this bug doesn't affect Cyanogenmod.

**Comment by gitgud-software** [comment]
Oh look at that, the File Manager in Paranoid Android was broken, not Antox. Closing this.

**Comment by subliun** [comment]
I enjoyed this story.

**Comment by agilob** [comment]
Add a Toast "profile successfully exported", this is second or third issue about the same.

**Comment by subliun** [comment]
@agilob there already is one...
