### ISSUE TITLE
Can't compile: No ToxEventListener

### ISSUE THREAD

**Issue by HongyuGong** [subliun/Antox#228]
Hi, this code imports the class 
"import im.tox.tox4j.core.callbacks.ToxEventListener" in ToxCallbackListener.scala.
However, I find that in tox4j_2.11.jar only contains ToxCoreEventListener.
Does the update of tox4j_2.11.jar cause such compilation failure?

**Comment by wiiam** [comment]
This was fixed in https://github.com/subliun/Antox/commit/466f5b49e963c24bf19e74a20eee6114f5c4100a

**Comment by HongyuGong** [comment]
It has been solved. Thanks!
