### ISSUE TITLE
Cannot install on Samsung Galaxy S1 with Cyanogen 9.0.0 (Android 4.0.4)

### ISSUE THREAD

**Issue by ulrichard** [subliun/Antox#23]
The behavior is the same for fdroid and direct download:
After accepting the permissions, it says "installing" and after a split second switches to "app not installed".

**Comment by louipc** [comment]
I believe this is a duplicate of https://github.com/subliun/Antox/issues/8 affecting android <4.4 Please check logs if you can to verify.

E/PackageParser(239): Package im.tox.antox has no certificates at entry AndroidManifest.xml; ignoring!

**Comment by susobaco** [comment]
9.0.0 cyanongen same error. Where logs are?

**Comment by subliun** [comment]
This should be fixed now. Please try again with the latest version from F-Droid.

**Comment by dionnejkelly** [comment]
Cant find Antox on F-Droid...

**Comment by louipc** [comment]
You must add the tox repo to fdroid https://repo.tox.im/android

**Comment by ulrichard** [comment]
Today's version installs, and works. Thanks!
