### ISSUE TITLE
deprecated method android studio build 

### ISSUE THREAD

**Issue by xavierle** [subliun/Antox#232]
when building antox on android studio to try committing somethings

 I have the actual errors

i have around 60 errors of this type : 

Error:(153) method getDrawable in class Resources is deprecated: see corresponding Javadoc for more information.

have you got an idea about what i am doing wrong

**Comment by wiiam** [comment]
Deprecated errors do not affect the build output. The reason for so many of these is because Antox aims to have support for older devices, which do not allow the use of some newer methods.

In most cases, any compilation errors that affect the build output will be under the deprecated errors.
