### ISSUE TITLE
Eclipse 

### ISSUE THREAD

**Issue by dionnejkelly** [subliun/Antox#24]
Is it possible to build Antox with eclipse ?

**Comment by subliun** [comment]
I don't use Eclipse and I'd recommend you use Android Studio. However it should be possible to build with eclipse and I'd imagine the build process would be very similar to AS. feel free to ask me or astonex on #tox-dev if you need more help

**Comment by dionnejkelly** [comment]
I went through the "hills and valleys" getting this to work on eclipse, but i stall at this line:
import rx.lang.scala.schedulers.{AndroidMainThreadScheduler, IOScheduler}
This wont import in all the scala files that have it. I downloaded the rx scala jars and add to the project from the Maven Repository.
Any idea ?
I wanted to post the error but am not arround my computer now, i will do so as soon as i get home.
I went on the tox-dev and didnt see any option to post this. Am new to all of the support sites for tox.
