### ISSUE TITLE
The antox client does not appear as online, then reconnect wifi

### ISSUE THREAD

**Issue by susobaco** [subliun/Antox#27]
I have found that when it is online, if you disconnect from the wireless network when reconnected, the client has the green button online, but friends (UTOX) does not appear as online

**Comment by susobaco** [comment]
If the udp option is enabled, it appears that this does not happen, is online in seconds

**Comment by reepr** [comment]
I'm getting this too. TCP is good for battery life but if the wifi connection cuts off anytime, Antox doesn't connect and see my friends online until I force restart it.
