### ISSUE TITLE
Nickname only in contacts view

### ISSUE THREAD

**Issue by nachfuellbar** [subliun/Antox#28]
https://github.com/Astonex/Antox/issues/652

issue still present in fdroid build

will you fix all old issues vom astonex repository or only issues which are on your repository?

**Comment by subliun** [comment]
This should be fixed now. 

Because I don't have any control over issues on astonex's repo, I'd rather people create new issues here if they still exist with the latest build.

**Comment by nachfuellbar** [comment]
It seems like this is really fixed

thanks
