### ISSUE TITLE
On Blackberry 10 Antox closes when "Registration" is clicked

### ISSUE THREAD

**Issue by srkunze** [subliun/Antox#3]
Cf. https://github.com/tux3/qTox/issues/847

**Comment by subliun** [comment]
I don't think there's any way I can fix this sadly. BlackBerry 10 doesn't support JNI, so Tox4j (the library that Antox uses to interface with toxcore) won't work. Perhaps you could open an issue on the [Tox4j repo](https://github.com/sonOfRa/tox4j/issues)?

**Comment by srkunze** [comment]
Nice chain of issues. :D
