### ISSUE TITLE
Feature: Optional message/chat logs

### ISSUE THREAD

**Issue by eosrei** [subliun/Antox#32]
Antox stores all messages in the logs. Can logging be optional?

Original issue: https://github.com/Astonex/Antox/issues/670

**Comment by subliun** [comment]
Do you want to be able to disable logs entirely or chose to disable them per-contact?

**Comment by eosrei** [comment]
I hadn't thought that far through, but it's reasonable to assume security conscious users would enjoy both options.

**Comment by subliun** [comment]
Ok. My plan is add a setting to disable logging globally that will wipe the message logs from all contacts on logout. Would that satisfy your needs?

**Comment by eosrei** [comment]
Sure, that'll handle the issue.

**Comment by eosrei** [comment]
Awesome thanks!
