### ISSUE TITLE
Antox not connecting to network

### ISSUE THREAD

**Issue by leugenea** [subliun/Antox#35]
I've tried to import existing account and creating a new one from Antox.
In profile menu status is "online". But friend requests from Antox don't reach my desktop client (qTox) which works just fine. Neither do friend requests from qTox to Antox.
Tested on Nexus 7 (2013, WiFi, codename FLO) and Nexus 4 (codename MAKO) (over WiFi and cellular network). I've tried to enable/disable UDP but this didn't work too.

**Comment by eternal-sorrow** [comment]
Confirm. Tried to add groupbot, with no success.

**Comment by subliun** [comment]
I can't reproduce this without more information, sorry. At this point I think this might be a toxcore issue, which you can report at https://github.com/irungentoo/toxcore

**Comment by eternal-sorrow** [comment]
If you tell me how to get any additional information, I'll provide it.
