### ISSUE TITLE
Crashes on registration

### ISSUE THREAD

**Issue by Binero** [subliun/Antox#36]
I downloaded the latest APK and installed it. 

When I type in a user name and hit register, Antox crashes. I am running Android lollipop 5.0.1 on a ASUS Google Nexus 7 2013 LTE device. My device is rooted if that could be a problem.

**Comment by subliun** [comment]
Root shouldn't be a problem. Where did you get the apk from? Make sure you're using the latest build, also try F-Droid if you can, that way you get bugfixes and updates automatically.

**Comment by Binero** [comment]
I got the APK from the GitHub main page. I would try F-Droid, but Antox isn't in the repos for me.

**Comment by subliun** [comment]
This should be fixed now, try the latest build. The crash was due to a link error with libkaliumjni.

In F-Droid you have to add https://repo.tox.im/android as a new repository to get access to Antox.

**Comment by Binero** [comment]
Work now. :-)
