### ISSUE TITLE
Connection does not carry over

### ISSUE THREAD

**Issue by smalltock** [subliun/Antox#37]
When moving from one connection, say Wifi, to another connection, for instance LTE, Antox loses its connection and doesn't reconnect until focused. I don't know if this happens while it's in the foreground, but it certainly happens when in the background.

**Comment by smalltock** [comment]
I take that back. Focusing Antox doesn't fix it. Have to kill it and restart.

**Comment by subliun** [comment]
Hopefully this is fixed now. Please reopen if it isn't.
