### ISSUE TITLE
First four letters of text is cut off...

### ISSUE THREAD

**Issue by dcharles525** [subliun/Antox#39]
When sending messages the message being received is cut for four characters. Also odd characters are sent when sending to any other client.

![screenshot from 2015-04-27 20 44 54](https://cloud.githubusercontent.com/assets/4961680/7360889/744b6b74-ed1e-11e4-8085-7269d65fab27.png)

![screenshot_2015-04-27-20-45-06](https://cloud.githubusercontent.com/assets/4961680/7360903/b624cd74-ed1e-11e4-9c0d-bc7f2f917ed3.png)

**Comment by subliun** [comment]
This and #40 are both caused by API incompatibility between Antox and qTox. Make sure both clients are up to date and are using the new api.

**Comment by dcharles525** [comment]
@subliun where can I find the latest apk? The links in the readme are non-updated apks.

**Comment by subliun** [comment]
You'll have to use F-Droid or join the Google+ group. The links in the readme are no longer being updated apparently.

**Comment by dcharles525** [comment]
@subliun I tried apks from the fdroid and google play, both of them didn't work.

**Comment by dcharles525** [comment]
@subliun After doing some digging, it looks like builds are broken... The last build was the 26th which was before the new api merge I think.
