### ISSUE TITLE
File transfers fail

### ISSUE THREAD

**Issue by dcharles525** [subliun/Antox#40]
Can no longer do file transfers.

![screenshot from 2015-04-27 20 49 03](https://cloud.githubusercontent.com/assets/4961680/7360922/e03027ee-ed1e-11e4-91f3-ddb7b416dc0a.png)

![screenshot apr 27 2015 8-48-52 pm](https://cloud.githubusercontent.com/assets/4961680/7360927/e8970330-ed1e-11e4-98c1-f6cc611c36c7.png)

**Comment by zetok** [comment]
Can't reproduce on ``0.22``, mind providing exact steps or closing issue?
