### ISSUE TITLE
ChromeOS Not working

### ISSUE THREAD

**Issue by ajay340** [subliun/Antox#46]
Downloaded it on ChromeOS and it won't launch

**Comment by subliun** [comment]
I cannot test this because I don't own a Chromebook. Perhaps @stqism will be able to help.

**Comment by Thursfield** [comment]
I get it going, but only if I register incognito. I found it annoying that you have to actually press the arrow  with the mouse courser to find a message. Could this be fixed?

**Comment by subliun** [comment]
ChromeOS is no longer supported afaik. At some point perhaps support will be restored but it is not high priority especially as Antox does not yet have a proper tablet layout.
