### ISSUE TITLE
File transfer extremely slow

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#47]
Antox->qTox

Antox from your fdroid repo, qtox build from sources.

Both devices in the same network. Max. transmission speed was 5kb/s. Using old API (3months ago) I'm sure picture transfer was instant, >5mb/s.

**Comment by subliun** [comment]
5kb/s is slower than I've ever seen it, I usually get 200kb/s on my local network. Is this still an issue with qTox's latest transfer speed optimisations (https://github.com/tux3/qTox/commit/7cb98b90c7b7754cf9c876228ab62fac79d906d0 - calling tox_iterate more often)? I'll probably implement something similar to see if the speed improves.

**Comment by agilob** [comment]
cant reproduce anymore.
