### ISSUE TITLE
Request : send contact

### ISSUE THREAD

**Issue by vincenttschanz** [subliun/Antox#50]
Apparently it's not possible to send a contact to another one. It's not even possible to get the ID of a contact in order to copy it and to manually send it.

Also, If someone send me an id, I can't copy it from the message I received.

**Comment by subliun** [comment]
Unfortunately this is a toxcore limitation. It doesn't provide Antox with a full Tox ID for all contacts. I'd suggest opening an issue on https://github.com/irungentoo/toxcore

>Also, If someone send me an id, I can't copy it from the message I received.
This however, is an Antox issue. I'm working to resolve it. see: https://github.com/subliun/Antox/issues/42

**Comment by vincenttschanz** [comment]
Thanks a lot!
