### ISSUE TITLE
Unsent typing lost when switching threads/conversations

### ISSUE THREAD

**Issue by StorytellerKaji** [subliun/Antox#52]
I noticed that I lose what I have typed so far if I get a message from another friend, and I switch to that conversation to see what was sent, and then come back to the other message to finish my typing. When I return to it, anything I had typed but not sent is just gone. Not sure if this is a bug or a known issue, but I don't remember it happening before Antox was reworked, though I could be wrong.

**Comment by subliun** [comment]
Depends on #53 to be done properly.
