### ISSUE TITLE
Antox doesn't 'see' contacts 

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#55]
Hard to explain what happens...
I updated antox twice today, after the last update antox connects to the network and I see online status on qtox, but messages are not received.
Antox doesn't see statuses or even nicknames and messages to contacts aren't sent, they also don't appear in chat window. Recent conversations are empty.
![screenshot_2015-05-20-17-38-28](https://cloud.githubusercontent.com/assets/2544251/7731347/b0d859d4-ff17-11e4-8627-e693131785da.png)

Messages from qtox are delivered:
![ff1](https://cloud.githubusercontent.com/assets/2544251/7731363/ca4750dc-ff17-11e4-8206-84f0a8fff673.png)

**Comment by agilob** [comment]
ymm restarting mobile phone fixed the problem oO

**Comment by subliun** [comment]
This is an issue, and I think I might know the cause.

**Comment by agilob** [comment]
bump?
