### ISSUE TITLE
Antox forgets my account?

### ISSUE THREAD

**Issue by Doom032** [subliun/Antox#58]
I don't really understand what just happened so stay with me.

What I did:

1) Install Antox from F-Droid
2) Register an account incognito (because registering normally was giving errors)
3) Use Antox for a while, testing it out
4) Do other stuff, leave phone idle
5) Come back to phone, open Antox
6) Be greeted by the "register" screen again, seemingly no way to get back to my account. Tried to re-import it but no idea where it would be anyway or if that's possible
7) Try to register incognito with the same name, maybe that works
8) Find my Tox ID is changed, so nope, I lost my new account

Any idea what happened?

**Comment by subliun** [comment]
Very sorry about that. I introduced a UserDB bug while fixing another issue a few days ago. It should be fixed now.
