### ISSUE TITLE
No Audio or Video anywhere

### ISSUE THREAD

**Issue by gerroon** [subliun/Antox#66]
Hi

I just downloaded r100 and setup a friend.  I do not see any video or audio option anywhere however based on the pics on the front page it looks like there is audio and video support.

The client has a linux friend using utox.

I am on CMod Android 4.4.4

**Comment by Astonex** [comment]
Those icons in the image were just placeholders at the time. They've since been removed to make it clear that A/V isn't implemented but the image hasn't been updated.

Calling will be implemented pretty soon

**Comment by gerroon** [comment]
@Astonex 
Thanks for the follow up. I will keep testing it.


Keep up the good work

**Comment by zoff99** [comment]
any news on that? is anybody working on audio/video?

**Comment by subliun** [comment]
I'll be working on AV at some point.
