### ISSUE TITLE
Cannot copy messages sometimes

### ISSUE THREAD

**Issue by Doom032** [subliun/Antox#77]
Sometimes messages seem to be uncopyable, even though other messages around them still are. Usually this seems to happen with messages with links in them. Worst case links are automatically added to a Tox ID you sent to Antox(I guess it thinks they're phone numbers?) and you can't copy the Tox ID after receiving it. Restarting Antox seems to fix it.

**Comment by ericthefish** [comment]
is this the same as Issue #42 ?  Sounds like it.

**Comment by Doom032** [comment]
Sorry, I'm a bit chaotic lately! I forget what issues I've even commented on!
