### ISSUE TITLE
Can't install Antox after its uninstallation.

### ISSUE THREAD

**Issue by SkyWheel** [subliun/Antox#8]
I had installed Antox (new .apk-file). Then I tried to install Antox from F-Droid repo, but before that I needed to uninstall previous version. I've uninstalled it from F-Droid. Now I can not install it from any source.
I've tried: delete cache of F-Droid, delete system cache and dalvik cache, find any traces after Antox in file system.
What else I can do to fix this issue?

**Comment by subliun** [comment]
I don't use F-Droid, and I don't really know what would be causing this issue. :(
Have you tried pressing refresh in F-Droid?

**Comment by louipc** [comment]
I have this same problem I will try to post a log in the coming days.

**Comment by SkyWheel** [comment]
I've also tried to install Antox.apk.
So this error after incorrect uninstallation by F-Droid.
But I'm interesting where could I find Antox traces  to delete them?

**Comment by louipc** [comment]
The errors I get are:
02-10 00:34:57.418 E/SurfaceTexture(122): [android/com.android.internal.app.ResolverActivity] drainQueueLocked: SurfaceTexture has been abandoned!
02-10 00:35:00.821 E/PackageParser(239): Package im.tox.antox has no certificates at entry AndroidManifest.xml; ignoring!
02-10 00:35:01.142 E/org.fdroid.fdroid.AppDetails(19616): Installer aborted with errorCode: 2

**Comment by SkyWheel** [comment]
louipc, did you try to install directly apk-file?

**Comment by louipc** [comment]
Yes I tried with apk, with fdroid, uninstalling fdroid, and trying again. Nothing works, but subliun provided me with another build that works. It seems like they need to fix their package signing keys or something, because the official build is uninstallable. It might be possible to download the package and add your own certificate, but I'm not sure how to do that right now.

**Comment by louipc** [comment]
SkyWheel what version of android do you use? I have 4.0.3

**Comment by SkyWheel** [comment]
louipc, I use build on 4.2.1
I had some doubts about certificates, but I didn't know how to check this assumption...
subliun, could you please provide me another build too?
Thank you in advance!:)

**Comment by tuxayo** [comment]
Same bug, I would like to try to delete app data before uninstalling but I can't find the previous version to reinstall it.

**Comment by markus1540** [comment]
Posting another LogCat from duplicate #17 
```
02-14 22:19:27.648 D/szipinf ( 1504): Initializing inflate state
02-14 22:19:28.023 D/dalvikvm( 1504): GC_FOR_MALLOC freed 922K, 40% free 7327K/12103K, external 2855K/3343K, paused 134ms
02-14 22:19:28.187 D/dalvikvm( 1504): GC_FOR_MALLOC freed 239K, 40% free 7302K/12103K, external 2677K/3343K, paused 95ms
02-14 22:19:28.421 W/PackageParser( 1504): Exception reading AndroidManifest.xml in /data/app/vmdl-202325236.tmp
02-14 22:19:28.421 W/PackageParser( 1504): java.lang.SecurityException: META-INF/TOXFOUND.SF has invalid digest for res/drawable-mdpi-v4/ic_action_camera.png in /data/app/vmdl-202325236.tmp
02-14 22:19:28.421 W/PackageParser( 1504):  at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:130)
02-14 22:19:28.421 W/PackageParser( 1504):  at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:357)
02-14 22:19:28.421 W/PackageParser( 1504):  at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:265)
02-14 22:19:28.421 W/PackageParser( 1504):  at java.util.jar.JarFile.getInputStream(JarFile.java:389)
02-14 22:19:28.421 W/PackageParser( 1504):  at android.content.pm.PackageParser.loadCertificates(PackageParser.java:343)
02-14 22:19:28.421 W/PackageParser( 1504):  at android.content.pm.PackageParser.collectCertificates(PackageParser.java:514)
02-14 22:19:28.421 W/PackageParser( 1504):  at com.android.server.PackageManagerService.installPackageLI(PackageManagerService.java:6034)
02-14 22:19:28.421 W/PackageParser( 1504):  at com.android.server.PackageManagerService.access$2200(PackageManagerService.java:142)
02-14 22:19:28.421 W/PackageParser( 1504):  at com.android.server.PackageManagerService$5.run(PackageManagerService.java:4777)
02-14 22:19:28.421 W/PackageParser( 1504):  at android.os.Handler.handleCallback(Handler.java:587)
02-14 22:19:28.421 W/PackageParser( 1504):  at android.os.Handler.dispatchMessage(Handler.java:92)
02-14 22:19:28.421 W/PackageParser( 1504):  at android.os.Looper.loop(Looper.java:130)
02-14 22:19:28.421 W/PackageParser( 1504):  at android.os.HandlerThread.run(HandlerThread.java:60)
02-14 22:19:28.421 E/PackageParser( 1504): Package im.tox.antox has no certificates at entry AndroidManifest.xml; ignoring!
02-14 22:19:28.718 D/dalvikvm( 1504): GC_EXPLICIT freed 658K, 39% free 7492K/12103K, external 2677K/3343K, paused 116ms
```

**Comment by kodispot** [comment]
Same Here And I Dont Use F-Droid

**Comment by Projekt-43** [comment]
Same here with f-droid

>02-15 14:39:13.153 D/dalvikvm(555): GC_CONCURRENT freed 1154K, 13% free 26570K/30360K, paused 6ms+9ms, total 115ms
>02-15 14:39:13.153 D/dalvikvm(555): WAIT_FOR_CONCURRENT_GC blocked 96ms
>02-15 14:39:13.173 W/PackageParser(555): Exception reading AndroidManifest.xml in /data/app/vmdl-1498627579.tmp
>02-15 14:39:13.173 W/PackageParser(555): java.lang.SecurityException: META-INF/TOXFOUND.SF has invalid digest for res/drawable-mdpi-v4/ic_action_camera.png in /data/app/vmdl-1498627579.tmp
>02-15 14:39:13.173 W/PackageParser(555): 	at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:131)
>02-15 14:39:13.173 W/PackageParser(555): 	at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:350)
>02-15 14:39:13.173 W/PackageParser(555): 	at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:258)
>02-15 14:39:13.173 W/PackageParser(555): 	at java.util.jar.JarFile.getInputStream(JarFile.java:378)
>02-15 14:39:13.173 W/PackageParser(555): 	at android.content.pm.PackageParser.loadCertificates(PackageParser.java:462)
>02-15 14:39:13.173 W/PackageParser(555): 	at android.content.pm.PackageParser.collectCertificates(PackageParser.java:653)
>02-15 14:39:13.173 W/PackageParser(555): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:9989)
>02-15 14:39:13.173 W/PackageParser(555): 	at com.android.server.pm.PackageManagerService.access$2100(PackageManagerService.java:214)
>02-15 14:39:13.173 W/PackageParser(555): 	at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:7844)
>02-15 14:39:13.173 W/PackageParser(555): 	at android.os.Handler.handleCallback(Handler.java:725)
>02-15 14:39:13.173 W/PackageParser(555): 	at android.os.Handler.dispatchMessage(Handler.java:92)
>02-15 14:39:13.173 W/PackageParser(555): 	at android.os.Looper.loop(Looper.java:137)
>02-15 14:39:13.173 W/PackageParser(555): 	at android.os.HandlerThread.run(HandlerThread.java:60)
>02-15 14:39:13.173 E/PackageParser(555): Package im.tox.antox has no certificates at entry AndroidManifest.xml; ignoring!
>02-15 14:39:13.303 D/dalvikvm(555): GC_EXPLICIT freed 371K, 14% free 26249K/30360K, paused 4ms+23ms, total 128ms

**Comment by tuxayo** [comment]
Finally works with version 0.15.59 from F-Droid!
A lot of force closes compared to previous versions, (old Antox) anyone else experience such instabilities?

**Comment by subliun** [comment]
This should be fixed now.

@tuxayo currently sending or receiving a file or attempting an audio call will crash Antox. There's nothing I can do about this as it's a bug in tox4j. If something else is causing a crash please open a new issue describing the problem (with logs from the crash, preferably) and I'll look into it.

**Comment by Projekt-43** [comment]
@subliun I confirm that it's fixed for me too, with F-Droid & same device.
I didn't had time to test further, but it"s installed & profile is imported.

Thanx!

**Comment by louipc** [comment]
Works now.

**Comment by subliun** [comment]
I'll assume this is fixed for everyone and close it now. If anyone still has issues installing the latest build from F-Droid comment and I'll reopen.
