### ISSUE TITLE
Contact list bug

### ISSUE THREAD

**Issue by ProMcTagonist** [subliun/Antox#83]
I have three contacts: groupbot, my own computer, and an ID that never came online to confirm.

Groupbot is at the top, my computer is in the middle, and the ID is at the bottom.

When do a search that leaves only the ID, the ID appears to have Groupbot's status.

I'm using Antox 0.22, but all of them for a while have been that version, so all I can tell you is that I updated from fdroid today.

**Comment by subliun** [comment]
I can't reproduce this

**Comment by subliun** [comment]
Yeah I can't. Reopen if you can.
