### ISSUE TITLE
Misalignment in sidebar

### ISSUE THREAD

**Issue by ProMcTagonist** [subliun/Antox#84]
When an entry in the sidebar is tapped, the highlight around the button text and icon is a little higher than the text and icon. Antox from fdroid today.

**Comment by subliun** [comment]
Fixing the sidebar depends on the design support library, which is currently incompatible with Scala 2.11.16. This will be fixed when 2.11.17 is released.

**Comment by ProMcTagonist** [comment]
Alright, thanks for the response. Keep up the good work :)
