### ISSUE TITLE
Crashes at login on BlackBerry Android 4.3

### ISSUE THREAD

**Issue by oparoz** [subliun/Antox#92]
I know you're probably not supporting that version of Android since it runs on QNX and not Linux, but I just wanted to let you know in case there was a common denominator with other reports of crashes after pressing the "register" button. Tried the latest 0.22 and 0.15 from the 31st of May.

**Comment by subliun** [comment]
BlackBerry is not supported by the tox4j library that Antox uses to interface with toxcore, so Antox cannot run on BlackBerry devices. 
Please see:
https://github.com/subliun/Antox/issues/3
https://github.com/tox4j/tox4j/issues/29
